ALTER TABLE users
  ADD COLUMN IF NOT EXISTS university VARCHAR(150) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS field_of_study VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS year_of_study TINYINT DEFAULT NULL;
